name: 🏎️ (BASH) Manual Umbraco Cloud Deployment

# Manually trigger and run deployment
# Optionally skip the cloud-sync
on: 
  workflow_dispatch:
    inputs:
      perform_sync:
        description: 'Run Sync operation First'
        type: boolean
        default: true

jobs:
  cloud-sync:
    name: "Synchronize with Cloud"
    runs-on: ubuntu-latest
    env: 
      projectId: ${{ vars.PROJECT_ID }}
      apiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
    steps:
    - name: Run sync
      uses: ./.github/workflows/bash-cloud-sync.yml
      if: ${{ inputs.perform_sync }}
      with:
        projectId: ${{ env.projectId }}
        umbracoCloudApiKey: ${{ env.apiKey }}

    - name: Skip sync
      if: ${{ inputs.perform_sync == false}}
      run: exit 0

  
  # Package and Deploy to Umbraco Cloud
  cloud-deployment:
    name: "Deploy to Cloud"
    uses: ./.github/workflows/bash-cloud-deployment.yml
    needs: cloud-sync
    with:
      projectId: ${{ vars.PROJECT_ID }}
    secrets:
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
