name: pipeline

on:
  push:
    branches: [ main ]
    
env:
  PATH_TO_CSPROJ: src/UmbracoProject/UmbracoProject.csproj
  PROJECT_ALIAS: pipelines-r-us
      
jobs:
#  build:
#    name: Build and test
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Setup .Net Core
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: '7.0.x'
          
#      - name: Install Dependencies
#        run: dotnet restore $PATH_TO_CSPROJ
        
#      - name: Build
#        run: dotnet build $PATH_TO_CSPROJ --configuration Release --no-restore
        
#      - name: Test
#        run: dotnet test $PATH_TO_CSPROJ --no-restore --verbosity normal
  preflight:
    name: Deployment Preflight Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Check for changes in Cloud
        id: cloud-changes
        uses: jesp209i/uc-changes-since-last-deployment@v0.1-beta19
        with:
          project-alias: ${{ env.PROJECT_ALIAS }}
          api-key: ${{ secrets.API_KEY }}
          workspace: ${{ github.workspace }}
      - name: Apply Diffs
        if: steps.cloud-changes.outputs.REMOTE_CHANGES == 'true'
        run: sh echo ${{ steps.cloud-changes.outputs.PATCH_FILE }}
        shell: bash

#  publish:
#    name: Publish to Cloud
#    needs: preflight
#    runs-on: ubuntu-latest
#    steps:
#      - name: build frontend
#        uses: actions/checkout@v3
#      
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 14.x
#      - run: npm i && npm run build

#      - name: Create Deployment Meta
#        id: deployment-meta
#        uses: jesp209i/uc-prepare-deployment-action@v0.0.6-beta5
#        with:
#          project-alias: ${{ env.PROJECT_ALIAS }}
#          api-key: ${{ secrets.API_KEY }}
#          commit-message: "Run number ${{github.run_number}}"

#      - name: Prepare Cloud Git Ignore
#        run: cp .cloudgitignore .gitignore
#        shell: bash

#      - name: Zip Source Code
#        run: zip -r sources.zip . -x ".git/*" ".github/*" "src/MyAwesomeProject.Code/bin/*" "src/MyAwesomeProject.Code/obj/*" "src/MyAwesomeProject.Web/bin/*" "src/MyAwesomeProject.Web/obj/*" "node_modules/*"
#        shell: bash
      
#      - name: Upload Zipped Artifact
#        uses: jesp209i/uc-upload-deployment@v0.2-beta4
#        with:
#          project-alias: ${{ env.PROJECT_ALIAS }}
#          deployment-id: ${{ steps.deployment-meta.outputs.DEPLOYMENT_ID }}
#          api-key: ${{ secrets.API_KEY }}
#          file-path: "${{ github.workspace }}/sources.zip"
      
#      - name: Request Start Deployment
#        uses: jesp209i/uc-start-deployment@v0.1-beta2
#        with:
#          project-alias: ${{ env.PROJECT_ALIAS }}
#          deployment-id: ${{ steps.deployment-meta.outputs.DEPLOYMENT_ID }}
#          api-key: ${{ secrets.API_KEY }}
        
#      - name: Wait for deployment completed
#        uses: jesp209i/uc-deployment-status@v0.2-beta7
#        with:
#          project-alias: ${{ env.PROJECT_ALIAS }}
#          deployment-id: ${{ steps.deployment-meta.outputs.DEPLOYMENT_ID }}
#          api-key: ${{ secrets.API_KEY }}
#          timeout-seconds: 600