name: (pwsh) 🚀 Umbraco Cloud Deployment pipeline

on:
  push:
    branches:
     - main
  workflow_dispatch:


jobs:
  bubber:
    name: "bubber"
    runs-on: ubuntu-latest
    steps:
      - name: "show my context"
        shell: pwsh
        run: Write-Host ${{GITHUB.EVENT.type}}

#  cloud-sync:
#    name: "Syncronize with Cloud"
#    uses: ./.github/workflows/pwsh-cloud-sync.yml
#    secrets:
#      projectId: ${{ secrets.PROJECT_ID }}
#      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}

  # Package and Deploy to Umbraco Cloud
#  cloud-deployment:
#    name: "Deploy to Cloud"
#    uses: ./.github/workflows/pwsh-cloud-deployment.yml
#    needs: cloud-sync
#    secrets:
#      projectId: ${{ secrets.PROJECT_ID }}
#      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}