name: pipeline

on:
  push:
    branches:
     - main
     - using_project-id
     - powershell

env:
  projectId: ${{ vars.PROJECT_ID }}
  umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}

jobs:

  publish:
    name: Zip and Publish to Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Deployment Meta
        id: deployment-meta
        run: $GITHUB_WORKSPACE/.github/workflows/scripts/create_deployment.sh $projectId $umbracoCloudApiKey "Run number ${{github.run_number}}"
        shell: bash

      - name: Zip Source Code
        run: zip -r sources.zip . -x ".git/*" ".github/*" "src/UmbracoProject/bin/*" "src/UmbracoProject/obj/*" "node_modules/*"
        shell: bash

      - name: Post Zipped Artifact
        run: $GITHUB_WORKSPACE/.github/workflows/scripts/upload_package.sh $projectId ${{ steps.deployment-meta.outputs.DEPLOYMENT_ID }} $umbracoCloudApiKey $GITHUB_WORKSPACE/sources.zip
        shell: bash

      - name: Request Start Deployment
        run: $GITHUB_WORKSPACE/.github/workflows/scripts/start_deployment.sh $projectId ${{ steps.deployment-meta.outputs.DEPLOYMENT_ID }} $umbracoCloudApiKey
        shell: bash

      - name: Wait for deployment completed
        run: pwsh -command ".\$GITHUB_WORKSPACE\.github\workflows\ps\get_deployment_status.ps1 -BaseUrl https://api.cloud.umbraco.com -ProjectId $projectId -DeploymentId ${{ steps.deployment-meta.outputs.DEPLOYMENT_ID }} -ApiKey $umbracoCloudApiKey"
        shell: pwsh
