name: pipeline

on:
  push:
    branches:
     - main
     - using_project-id
     - powershell

env:
  projectId: ${{ vars.PROJECT_ID }}
  umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
  baseUrl : https://api.cloud.umbraco.com

jobs:

  publish:
    name: Zip and Publish to Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Deployment Meta PWSH
        id: deployment-meta
        shell: pwsh
        run: ${{GITHUB.WORKSPACE}}/.github/workflows/ps/create_deployment.ps1 -BaseUrl ${{env.baseUrl}} -ProjectId ${{ env.projectId }} -ApiKey ${{ env.umbracoCloudApiKey }} -CommitMessage "Run number ${{github.run_number}}"

      #- name: Create Deployment Meta
      #  id: deployment-meta-sh
      #  run: $GITHUB_WORKSPACE/.github/workflows/scripts/create_deployment.sh $projectId $umbracoCloudApiKey "Run number ${{github.run_number}}"
      #  shell: bash

      - name: Zip Source Code
        run: zip -r sources.zip . -x ".git/*" ".github/*" "src/UmbracoProject/bin/*" "src/UmbracoProject/obj/*" "node_modules/*"
        shell: bash

      - name: Post Zipped Artifact PWSH
        shell: pwsh
        run: ${{GITHUB.WORKSPACE}}/.github/workflows/ps/upload_package.ps1 -BaseUrl ${{env.baseUrl}} -ProjectId ${{ env.projectId }} -DeploymentId ${{ steps.deployment-meta.outputs.DEPLOYMENT_ID }} -ApiKey ${{ env.umbracoCloudApiKey }} -FilePath ${{ GITHUB.WORKSPACE }}/sources.zip

      #- name: Post Zipped Artifact
      #  run: $GITHUB_WORKSPACE/.github/workflows/scripts/upload_package.sh $projectId ${{ steps.deployment-meta.outputs.DEPLOYMENT_ID }} $umbracoCloudApiKey $GITHUB_WORKSPACE/sources.zip
      #  shell: bash

      - name: Request Start Deployment PWSH
        shell: pwsh
        run: ${{ GITHUB.WORKSPACE }}/.github/workflows/ps/start_deployment.ps1 -BaseUrl ${{env.baseUrl}} -ProjectId ${{ env.projectId }} -DeploymentId ${{ steps.deployment-meta.outputs.DEPLOYMENT_ID }} -ApiKey ${{ env.umbracoCloudApiKey }}
     # - name: Request Start Deployment
     #  run: $GITHUB_WORKSPACE/.github/workflows/scripts/start_deployment.sh $projectId ${{ steps.deployment-meta.outputs.DEPLOYMENT_ID }} $umbracoCloudApiKey
     #   shell: bash

      - name: Wait for deployment completed PWSH
        shell: pwsh
        run: ${{ GITHUB.WORKSPACE }}/.github/workflows/ps/get_deployment_status.ps1 -BaseUrl ${{ env.baseUrl }} -ProjectId ${{ env.projectId }} -DeploymentId ${{ steps.deployment-meta.outputs.DEPLOYMENT_ID }} -ApiKey ${{ env.umbracoCloudApiKey }}
