name: (pwsh) 🚀 Umbraco Cloud Deployment pipeline

on:
  push:
    branches:
     - main

jobs:
  cloud-sync:
    name: "Syncronize with Cloud"
    uses: ./.github/workflows/pwsh-cloud-sync.yml
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}

  cloud-deployment:
    name: "Deploy to Cloud"
    needs: cloud-sync
    uses: ./.github/workflows/pwsh-cloud-deployment.yml
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
