name: pipeline

on:
  push:
    branches:
     - main
     - using_project-id
     - powershell
     - pwsh-get-changes

env:
  projectId: ${{ vars.PROJECT_ID }}
  umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}

jobs:
  cloud-sync:
    uses: jesp209i/pipelines-r-us/.github/workflows/cloud-sync.yml@pwsh-get-changes
    with:
      projectId: ${{ vars.PROJECT_ID }}
    secrets:
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}

  publish:
    needs: cloud-sync
    uses: jesp209i/pipelines-r-us/.github/workflows/deployment.yml@pwsh-get-changes
    with:
      projectId: ${{ vars.PROJECT_ID }}
    secrets:
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}