name: 🚀 Cloud Deployment pipeline

on:
  push:
    branches:
     - main

jobs:
  cloud-sync:
    name: "Syncronize with Cloud"
    uses: ./.github/workflows/cloud-sync.yml
    with:
      projectId: ${{ vars.PROJECT_ID }}
    secrets:
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}

  cloud-deployment:
    name: "Deploy to Cloud"
    needs: cloud-sync
    uses: ./.github/workflows/cloud-deployment.yml
    with:
      projectId: ${{ vars.PROJECT_ID }}
    secrets:
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
