name: (pwsh) 💫 Manual Run Deployment Status 

# Manually trigger a deployemnt status
# DeploymentId required
on: 
  workflow_dispatch:
    inputs:
      deployment_id:
        description: 'DeploymentId'
        type: string
        required: true

jobs:
    cloud-deployment-status:
        name: Get Deployment Status Manually
        runs-on: ubuntu-latest
        env: 
            projectId: ${{ vars.PROJECT_ID}}
            apiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY}}
            deploymentId: ${{ inputs.deployment_id }}
        steps:
            - uses: actions/checkout@v4
            - name: Get status of deployment 
              shell: pwsh
              run: >
                ${{GITHUB.WORKSPACE}}/.github/powershell/Test-DeploymentStatus.ps1 
                -ProjectId ${{ env.projectId }} 
                -DeploymentId ${{ env.deploymentId }} 
                -ApiKey ${{ env.apiKey }}
                -UseHardFail 0
