name: 🏎️ (pwsh) Manual Umbraco Cloud Deployment (Hack)

# Manually trigger and run run
# Optionally skip the cloud-sync
on: 
  workflow_dispatch:
    inputs:
      perform_sync:
        description: 'Run Sync operation First'
        type: boolean
        default: true

jobs:
  cloud-sync:
    name: "Synchronize with Cloud"
    uses: ./.github/workflows/pwsh-cloud-sync.yml
    if: ${{ inputs.perform_sync }}
    with:
      projectId: ${{ vars.PROJECT_ID }}
    secrets:
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
  
  # Package and Deploy to Umbraco Cloud
  cloud-deployment:
    name: "Deploy to Cloud"
    uses: ./.github/workflows/pwsh-cloud-deployment.yml
    with:
      projectId: ${{ vars.PROJECT_ID }}
    secrets:
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
