name: Manual Cloud Sync

on: workflow_dispatch

jobs:
  cloud-sync:
    uses: ./.github/workflows/cloud-sync.yml
    with:
      projectId: ${{ vars.PROJECT_ID }}
    secrets:
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}