name: Manual Cloud Sync

on: workflow_dispatch

jobs:
  cloud-sync:
    uses: jesp209i/pipelines-r-us/.github/workflows/cloud-sync.yml@pwsh-get-changes
    with:
      projectId: ${{ vars.PROJECT_ID }}
    secrets:
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}