name: Manual Cloud Deployment

on: workflow_dispatch

jobs:
  cloud-deployment:
    uses: ./.github/workflows/cloud-deployment.yml
    with:
      projectId: ${{ vars.PROJECT_ID }}
    secrets:
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}